version: 2

sources:
    - name: flight_ods
      description: This is a snowflake 
      database: flight
      schema: flight_ods
      tables:
          - name: flights_data_raw
            description: flights_data_raw
    
    - name: flight_dwh
      description: This is a snowflake 
      database: flight
      schema: flight_ods
      tables:
          - name: dwh_flights
            description: flights_data_parsed